name: Build IPA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
     - uses: actions/checkout@v3
     - name: Compile
       run: make
     
     - name: Upload artifact
       uses: actions/upload-artifact@v3
       with:
        name: MuffinStoreJailed
        path: MuffinStoreJailed.ipa

on:
  push:
    branches:
      - main
  workflow_dispatch: # Add this line for manual triggers
